# set up day / month info
'''self.days = {
    SUNDAY: MONDAY,
    MONDAY: TUESDAY,
    TUESDAY: WEDNESDAY,
    WEDNESDAY: THURSDAY,
    THURSDAY: FRIDAY,
    FRIDAY: SATURDAY,
    SATURDAY: SUNDAY,
}
self.months = {
    JANUARY: FEBRUARY,
    FEBRUARY: MARCH,
    MARCH: APRIL,
    APRIL: MAY,
    MAY: JUNE,
    JUNE: JULY,
    JULY: AUGUST,
    AUGUST: SEPTEMBER,
    SEPTEMBER: OCTOBER,
    OCTOBER: NOVEMBER,
    NOVEMBER: DECEMBER,
    DECEMBER: JANUARY
}'''